language: python
python:
  - "2.7"

services:
  - docker

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
# script:
# - python manage.py test vsc

script:
  - docker-compose up -d
  - docker logs djangoproject_web
  - docker images
  - docker ps -a
  - bash starttest.sh

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master



